### ISSUE TITLE
It seems that the core code of CRITIC, particularly the part involving Google API search, is not implemented

### ISSUE THREAD

**Issue by zyg18181818** [microsoft/ProphetNet#67]

**Comment by WWWonderer** [comment]
+1

**Comment by ZubinGou** [comment]
Hi, thanks for your interest! 
To simplify, using text from the top result returned by the Google Search API is enough. Furthermore, due to budget constraints and the need for stable, reproducible results, we developed a Google and web page crawler with cache for our experiments (storing about 9GB of Google results from January-April 2023). This part of the code is complex, and we don't recommend trying it at the moment. We may consider organizing and open-sourcing the crawler separately in the future. Stay tuned for updates, and we appreciate your understanding!

**Comment by zyg18181818** [comment]
Thank you very much for taking the time to reply. I will continue to follow your work and look forward to future communication.
&nbsp;


周艺耕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhibin ***@***.***&gt;; 
发送时间: 2023年10月9日(星期一) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/ProphetNet] It seems that the core code of CRITIC, particularly the part involving Google API search, is not implemented (Issue #67)





 
Hi, thanks for your interest!
 To simplify, using text from the top result returned by the Google Search API is enough. Furthermore, due to budget constraints and the need for stable, reproducible results, we developed a Google and web page crawler with cache for our experiments (storing about 9GB of Google results from January-April 2023). This part of the code is complex, and we don't recommend trying it at the moment. We may consider organizing and open-sourcing the crawler separately in the future. Stay tuned for updates, and we appreciate your understanding!

**Comment by WWWonderer** [comment]
All right thank you for your reply! Looking forward to the open-source of the crawler!
